#!/bin/sh
if [ -z `which svn` ]
then
    echo "Missing svn"
    exit 255
fi

if [ -z `which wget` ]
then
    echo "Missing wget"
    exit 255
fi

if [ -z `which tar` ]
then
    echo "Missing tar"
    exit 255
fi

if [ -z `which git` ]
then
    echo "Missing git"
    exit 255
fi

if [ $# != 1 ]
then
  echo "USAGE: $0 NAME"
  exit 255
fi

echo $1 | grep -Eq '^[a-z0-9_.-]*$'
if [ $? != 0 ]
then
  echo "Illegal name $1"
  exit 255
fi

if [ -e $1 ]
then
  echo "$1 already exists"
  exit 255
fi

set -v
# Pull Konstrukt starterpack
svn export http://konstrukt.googlecode.com/svn/trunk/examples/starterpack_default $1
cd $1

# Pull krudt addon
git clone git://github.com/lsolesen/krudt.git var/krudt.git.$$
rm -rf var/krudt.git.$$/.git
cp -r var/krudt.git.$$/* .
rm -rf var/krudt.git.$$

# Pull bucket
mkdir -p thirdparty/bucket
git clone git://github.com/troelskn/bucket.git var/bucket.git.$$
rm -rf var/bucket.git.$$/.git
cp -r var/bucket.git.$$/* thirdparty/bucket
rm -rf var/bucket.git.$$

# Pull pdoext
svn export http://pdoext.googlecode.com/svn/trunk thirdparty/pdoext

# Set file permissions
chmod 777 log
chmod 777 var
# Remove installer
rm krudt
cd ..
set +v
echo "Krudt application created in $1"
